### ISSUE TITLE
New QBCore Function

### ISSUE THREAD

**Issue by JarretOnline** [NevoSwissa/CL-ThermiteMission#2]
Items are not received after heist completion. The latest version of QBcore introduces a new process for adding/removing items. See the message here: https://prnt.sc/4vUMBrhtMGh1

Are you able to accomodate the new method?

**Comment by gigitygamer** [comment]
Please...

**Comment by gigitygamer** [comment]
Why did you close it?

**Comment by JarretOnline** [comment]
We created our own thermite job using cw-raidjob | https://github.com/JarretOnline/cw-raidjobs
